import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const events = [
  {
    title: 'NeurIPS 2025',
    description: 'The 39th Annual Conference on Neural Information Processing Systems — the premier venue for ML research.',
    date: new Date('2025-12-07'),
    endDate: new Date('2025-12-13'),
    location: 'New Orleans, Louisiana, USA',
    isOnline: false,
    url: 'https://neurips.cc/Conferences/2025',
    source: 'neurips.cc',
    region: 'americas',
    regionArabic: 'الأمريكتان',
    category: 'conference',
    qualityScore: 0.95,
    scrapedAt: new Date(),
  },
  {
    title: 'ICML 2025',
    description: 'International Conference on Machine Learning — leading international academic conference in machine learning.',
    date: new Date('2025-07-13'),
    endDate: new Date('2025-07-19'),
    location: 'Vienna, Austria',
    isOnline: false,
    url: 'https://icml.cc/Conferences/2025',
    source: 'icml.cc',
    region: 'europe',
    regionArabic: 'أوروبا',
    category: 'conference',
    qualityScore: 0.92,
    scrapedAt: new Date(),
  },
  {
    title: 'AI Summit Dubai 2025',
    description: 'The leading AI business summit connecting enterprises with cutting-edge AI solutions in the Gulf region.',
    date: new Date('2025-10-14'),
    endDate: new Date('2025-10-15'),
    location: 'Dubai World Trade Centre, Dubai, UAE',
    isOnline: false,
    url: 'https://dubai.theaisummit.com/2025',
    source: 'theaisummit.com',
    region: 'middle-east',
    regionArabic: 'الشرق الأوسط',
    category: 'summit',
    qualityScore: 0.87,
    scrapedAt: new Date(),
  },
  {
    title: 'ICLR 2025',
    description: 'International Conference on Learning Representations — focused on deep learning and representation learning.',
    date: new Date('2025-04-24'),
    endDate: new Date('2025-04-28'),
    location: 'Singapore',
    isOnline: false,
    url: 'https://iclr.cc/Conferences/2025',
    source: 'iclr.cc',
    region: 'asia',
    regionArabic: 'آسيا',
    category: 'conference',
    qualityScore: 0.93,
    scrapedAt: new Date(),
  },
  {
    title: 'CVPR 2025',
    description: 'Conference on Computer Vision and Pattern Recognition — the top venue for computer vision research.',
    date: new Date('2025-06-10'),
    endDate: new Date('2025-06-17'),
    location: 'Nashville, Tennessee, USA',
    isOnline: false,
    url: 'https://cvpr.thecvf.com/Conferences/2025',
    source: 'thecvf.com',
    region: 'americas',
    regionArabic: 'الأمريكتان',
    category: 'conference',
    qualityScore: 0.91,
    scrapedAt: new Date(),
  },
  {
    title: 'PyTorch Workshop Cairo',
    description: 'Hands-on workshop covering PyTorch fundamentals, model training, and deployment for African AI practitioners.',
    date: new Date('2025-08-22'),
    endDate: new Date('2025-08-23'),
    location: 'Cairo, Egypt',
    isOnline: false,
    url: 'https://pytorch.org/events/cairo-workshop-2025',
    source: 'pytorch.org',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'workshop',
    qualityScore: 0.76,
    scrapedAt: new Date(),
  },
  {
    title: 'Machine Learning Nairobi Meetup',
    description: 'Monthly meetup for ML practitioners in Nairobi — talks, demos, and networking.',
    date: new Date('2025-06-18'),
    endDate: new Date('2025-06-18'),
    location: 'iHub, Nairobi, Kenya',
    isOnline: false,
    url: 'https://www.meetup.com/machine-learning-nairobi/events/2025-june',
    source: 'meetup.com',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'meetup',
    qualityScore: 0.71,
    scrapedAt: new Date(),
  },
  {
    title: 'AAAI 2025',
    description: 'Association for the Advancement of Artificial Intelligence — premier conference on AI research.',
    date: new Date('2025-02-25'),
    endDate: new Date('2025-03-04'),
    location: 'Philadelphia, Pennsylvania, USA',
    isOnline: false,
    url: 'https://aaai.org/conference/aaai/aaai-25',
    source: 'aaai.org',
    region: 'americas',
    regionArabic: 'الأمريكتان',
    category: 'conference',
    qualityScore: 0.90,
    scrapedAt: new Date(),
  },
  {
    title: 'AI Expo Africa 2025',
    description: 'Africa\'s biggest AI & cognitive systems event — showcasing AI innovation across the African continent.',
    date: new Date('2025-09-10'),
    endDate: new Date('2025-09-11'),
    location: 'Cape Town, South Africa',
    isOnline: false,
    url: 'https://aiexpoafrica.com/2025',
    source: 'aiexpoafrica.com',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'conference',
    qualityScore: 0.82,
    scrapedAt: new Date(),
  },
  {
    title: 'Global AI Summit Riyadh',
    description: 'Saudi Arabia\'s flagship AI event bringing together world leaders, tech giants, and AI innovators.',
    date: new Date('2025-09-08'),
    endDate: new Date('2025-09-10'),
    location: 'Riyadh, Saudi Arabia',
    isOnline: false,
    url: 'https://globalaisummit.com/riyadh-2025',
    source: 'globalaisummit.com',
    region: 'middle-east',
    regionArabic: 'الشرق الأوسط',
    category: 'summit',
    qualityScore: 0.89,
    scrapedAt: new Date(),
  },
  {
    title: 'Deep Learning Indaba 2025',
    description: 'Annual gathering to strengthen African machine learning community — workshops, tutorials, and research.',
    date: new Date('2025-08-04'),
    endDate: new Date('2025-08-09'),
    location: 'Accra, Ghana',
    isOnline: false,
    url: 'https://deeplearningindaba.com/2025',
    source: 'deeplearningindaba.com',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'workshop',
    qualityScore: 0.85,
    scrapedAt: new Date(),
  },
  {
    title: 'AI World Congress London',
    description: 'Premier AI conference in Europe bringing together business leaders and AI researchers.',
    date: new Date('2025-10-22'),
    endDate: new Date('2025-10-23'),
    location: 'London, United Kingdom',
    isOnline: false,
    url: 'https://aiworldcongress.com/london-2025',
    source: 'aiworldcongress.com',
    region: 'europe',
    regionArabic: 'أوروبا',
    category: 'conference',
    qualityScore: 0.84,
    scrapedAt: new Date(),
  },
  {
    title: 'PyData Berlin 2025',
    description: 'Community conference for the Python data ecosystem — pandas, NumPy, scikit-learn, and beyond.',
    date: new Date('2025-09-18'),
    endDate: new Date('2025-09-20'),
    location: 'Berlin, Germany',
    isOnline: false,
    url: 'https://berlin.pydata.org/2025',
    source: 'pydata.org',
    region: 'europe',
    regionArabic: 'أوروبا',
    category: 'conference',
    qualityScore: 0.79,
    scrapedAt: new Date(),
  },
  {
    title: 'ACL 2025',
    description: 'Annual Meeting of the Association for Computational Linguistics — premier NLP conference.',
    date: new Date('2025-07-27'),
    endDate: new Date('2025-08-01'),
    location: 'Vienna, Austria',
    isOnline: false,
    url: 'https://2025.aclweb.org',
    source: 'aclweb.org',
    region: 'europe',
    regionArabic: 'أوروبا',
    category: 'conference',
    qualityScore: 0.91,
    scrapedAt: new Date(),
  },
  {
    title: 'Machine Learning Tokyo Meetup',
    description: 'Bimonthly meetup for ML engineers and researchers in Tokyo — presentations and Q&A.',
    date: new Date('2025-07-08'),
    endDate: new Date('2025-07-08'),
    location: 'Tokyo, Japan',
    isOnline: false,
    url: 'https://www.meetup.com/ml-tokyo/events/july-2025',
    source: 'meetup.com',
    region: 'asia',
    regionArabic: 'آسيا',
    category: 'meetup',
    qualityScore: 0.73,
    scrapedAt: new Date(),
  },
  {
    title: 'AI Hackathon Abu Dhabi',
    description: '48-hour hackathon challenging participants to build AI solutions for UAE smart city challenges.',
    date: new Date('2025-11-14'),
    endDate: new Date('2025-11-16'),
    location: 'Abu Dhabi, UAE',
    isOnline: false,
    url: 'https://ai-hackathon-abudhabi.ae/2025',
    source: 'ai-hackathon-abudhabi.ae',
    region: 'middle-east',
    regionArabic: 'الشرق الأوسط',
    category: 'hackathon',
    qualityScore: 0.78,
    scrapedAt: new Date(),
  },
  {
    title: 'Generative AI Summit San Francisco',
    description: 'Dedicated conference on generative AI, LLMs, and foundation models — by builders, for builders.',
    date: new Date('2025-05-20'),
    endDate: new Date('2025-05-21'),
    location: 'San Francisco, California, USA',
    isOnline: false,
    url: 'https://genaisummit.ai/sf-2025',
    source: 'genaisummit.ai',
    region: 'americas',
    regionArabic: 'الأمريكتان',
    category: 'summit',
    qualityScore: 0.86,
    scrapedAt: new Date(),
  },
  {
    title: 'AI for Good Global Summit',
    description: 'UN platform for AI to accelerate progress towards the Sustainable Development Goals.',
    date: new Date('2025-07-08'),
    endDate: new Date('2025-07-10'),
    location: 'Geneva, Switzerland',
    isOnline: true,
    url: 'https://aiforgood.itu.int/summit/2025',
    source: 'itu.int',
    region: 'europe',
    regionArabic: 'أوروبا',
    category: 'summit',
    qualityScore: 0.88,
    scrapedAt: new Date(),
  },
  {
    title: 'Responsible AI Webinar Series: Bias & Fairness',
    description: 'Monthly webinar exploring bias detection and mitigation in production ML systems.',
    date: new Date('2025-06-25'),
    endDate: new Date('2025-06-25'),
    location: null,
    isOnline: true,
    url: 'https://responsibleai.org/webinar/bias-fairness-june-2025',
    source: 'responsibleai.org',
    region: 'worldwide',
    regionArabic: 'عالمي',
    category: 'webinar',
    qualityScore: 0.72,
    scrapedAt: new Date(),
  },
  {
    title: 'MLOps World 2025',
    description: 'The premier conference on machine learning operations — deployment, monitoring, and governance at scale.',
    date: new Date('2025-06-03'),
    endDate: new Date('2025-06-05'),
    location: 'Toronto, Canada',
    isOnline: false,
    url: 'https://mlopsworld.com/2025',
    source: 'mlopsworld.com',
    region: 'americas',
    regionArabic: 'الأمريكتان',
    category: 'conference',
    qualityScore: 0.83,
    scrapedAt: new Date(),
  },
  {
    title: 'AACL-IJCNLP 2025',
    description: 'Asia-Pacific Chapter of ACL — NLP research conference for the Asia-Pacific region.',
    date: new Date('2025-11-20'),
    endDate: new Date('2025-11-23'),
    location: 'Seoul, South Korea',
    isOnline: false,
    url: 'https://www.aacl2025.org',
    source: 'aacl2025.org',
    region: 'asia',
    regionArabic: 'آسيا',
    category: 'conference',
    qualityScore: 0.84,
    scrapedAt: new Date(),
  },
  {
    title: 'AI Ethics Symposium Brussels',
    description: 'European symposium on AI regulation, ethics, and the EU AI Act implications for businesses.',
    date: new Date('2025-10-09'),
    endDate: new Date('2025-10-10'),
    location: 'Brussels, Belgium',
    isOnline: false,
    url: 'https://aiethicseurope.eu/symposium-2025',
    source: 'aiethicseurope.eu',
    region: 'europe',
    regionArabic: 'أوروبا',
    category: 'conference',
    qualityScore: 0.80,
    scrapedAt: new Date(),
  },
  {
    title: 'Cairo AI Hackathon',
    description: '72-hour hackathon tackling Arabic NLP and computer vision challenges with prizes up to $10,000.',
    date: new Date('2025-07-25'),
    endDate: new Date('2025-07-27'),
    location: 'Cairo, Egypt',
    isOnline: false,
    url: 'https://cairoaihack.org/2025',
    source: 'cairoaihack.org',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'hackathon',
    qualityScore: 0.75,
    scrapedAt: new Date(),
  },
  {
    title: 'LLM Fine-tuning Workshop Online',
    description: 'Practical hands-on workshop: fine-tuning Llama 3, Mistral, and Gemma on custom datasets.',
    date: new Date('2025-06-14'),
    endDate: new Date('2025-06-14'),
    location: null,
    isOnline: true,
    url: 'https://llmworkshop.dev/fine-tuning-june-2025',
    source: 'llmworkshop.dev',
    region: 'worldwide',
    regionArabic: 'عالمي',
    category: 'workshop',
    qualityScore: 0.77,
    scrapedAt: new Date(),
  },
  {
    title: 'ECAI 2025',
    description: 'European Conference on Artificial Intelligence — bringing together AI research from across Europe.',
    date: new Date('2025-10-25'),
    endDate: new Date('2025-10-30'),
    location: 'Bologna, Italy',
    isOnline: false,
    url: 'https://ecai2025.eu',
    source: 'ecai2025.eu',
    region: 'europe',
    regionArabic: 'أوروبا',
    category: 'conference',
    qualityScore: 0.87,
    scrapedAt: new Date(),
  },
  {
    title: 'Bangalore ML Summit',
    description: 'India\'s largest ML practitioners gathering — product demos, research talks, and career expo.',
    date: new Date('2025-08-30'),
    endDate: new Date('2025-08-31'),
    location: 'Bangalore, India',
    isOnline: false,
    url: 'https://bangaloremlsummit.in/2025',
    source: 'bangaloremlsummit.in',
    region: 'asia',
    regionArabic: 'آسيا',
    category: 'summit',
    qualityScore: 0.80,
    scrapedAt: new Date(),
  },
  {
    title: 'KDD 2025',
    description: 'ACM SIGKDD Conference on Knowledge Discovery and Data Mining — 30+ years of data science research.',
    date: new Date('2025-08-03'),
    endDate: new Date('2025-08-07'),
    location: 'Washington D.C., USA',
    isOnline: false,
    url: 'https://kdd2025.kdd.org',
    source: 'kdd.org',
    region: 'americas',
    regionArabic: 'الأمريكتان',
    category: 'conference',
    qualityScore: 0.89,
    scrapedAt: new Date(),
  },
  {
    title: 'AI Bootcamp Lagos',
    description: '5-day intensive bootcamp on machine learning for African developers — free for accepted participants.',
    date: new Date('2025-07-14'),
    endDate: new Date('2025-07-18'),
    location: 'Lagos, Nigeria',
    isOnline: false,
    url: 'https://aibootcamplagos.org/2025',
    source: 'aibootcamplagos.org',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'course',
    qualityScore: 0.74,
    scrapedAt: new Date(),
  },
  {
    title: 'GITEX AI & Technology Week 2025',
    description: 'World\'s largest tech event featuring a major AI pavilion — Dubai\'s premier tech gathering.',
    date: new Date('2025-10-13'),
    endDate: new Date('2025-10-17'),
    location: 'Dubai World Trade Centre, Dubai, UAE',
    isOnline: false,
    url: 'https://gitex.com/gitex-global/2025',
    source: 'gitex.com',
    region: 'middle-east',
    regionArabic: 'الشرق الأوسط',
    category: 'conference',
    qualityScore: 0.88,
    scrapedAt: new Date(),
  },
  {
    title: 'Robotics: Science & Systems 2025',
    description: 'Single-track conference on robotics research — algorithms, systems, and applications.',
    date: new Date('2025-06-21'),
    endDate: new Date('2025-06-25'),
    location: 'Los Angeles, California, USA',
    isOnline: false,
    url: 'https://roboticsconference.org/2025',
    source: 'roboticsconference.org',
    region: 'americas',
    regionArabic: 'الأمريكتان',
    category: 'conference',
    qualityScore: 0.85,
    scrapedAt: new Date(),
  },
  {
    title: 'Zurich AI Meetup',
    description: 'Quarterly meetup for AI/ML professionals in Zurich — lightning talks and networking.',
    date: new Date('2025-06-12'),
    endDate: new Date('2025-06-12'),
    location: 'Zurich, Switzerland',
    isOnline: false,
    url: 'https://www.meetup.com/zurich-ai/events/june-2025',
    source: 'meetup.com',
    region: 'europe',
    regionArabic: 'أوروبا',
    category: 'meetup',
    qualityScore: 0.69,
    scrapedAt: new Date(),
  },
  {
    title: 'AI & Data Science Asia Summit',
    description: 'Pan-Asian summit covering AI trends, enterprise adoption, and data governance across APAC.',
    date: new Date('2025-09-23'),
    endDate: new Date('2025-09-24'),
    location: 'Singapore',
    isOnline: false,
    url: 'https://aianddata.asia/summit-2025',
    source: 'aianddata.asia',
    region: 'asia',
    regionArabic: 'آسيا',
    category: 'summit',
    qualityScore: 0.81,
    scrapedAt: new Date(),
  },
  {
    title: 'NLP4Africa Workshop 2025',
    description: 'Workshop dedicated to NLP research for African languages — low-resource language modeling.',
    date: new Date('2025-08-15'),
    endDate: new Date('2025-08-15'),
    location: 'Addis Ababa, Ethiopia',
    isOnline: false,
    url: 'https://nlp4africa.org/workshop-2025',
    source: 'nlp4africa.org',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'workshop',
    qualityScore: 0.78,
    scrapedAt: new Date(),
  },
  {
    title: 'AI in Healthcare Summit Dubai',
    description: 'AI applications in radiology, drug discovery, and clinical decision support for MENA healthcare.',
    date: new Date('2025-11-05'),
    endDate: new Date('2025-11-06'),
    location: 'Dubai, UAE',
    isOnline: false,
    url: 'https://aihealthcaresummit.ae/2025',
    source: 'aihealthcaresummit.ae',
    region: 'middle-east',
    regionArabic: 'الشرق الأوسط',
    category: 'summit',
    qualityScore: 0.82,
    scrapedAt: new Date(),
  },
  {
    title: 'World AI Cannes Festival',
    description: 'Annual celebration of AI creativity, art, and innovation on the French Riviera.',
    date: new Date('2025-02-10'),
    endDate: new Date('2025-02-12'),
    location: 'Cannes, France',
    isOnline: false,
    url: 'https://worldaicannes.com/2025',
    source: 'worldaicannes.com',
    region: 'europe',
    regionArabic: 'أوروبا',
    category: 'conference',
    qualityScore: 0.77,
    scrapedAt: new Date(),
  },
  {
    title: 'Practical AI Course: RAG Systems',
    description: 'Online 6-week course on building production-ready Retrieval-Augmented Generation systems.',
    date: new Date('2025-07-01'),
    endDate: new Date('2025-08-12'),
    location: null,
    isOnline: true,
    url: 'https://practicalai.io/courses/rag-systems-2025',
    source: 'practicalai.io',
    region: 'worldwide',
    regionArabic: 'عالمي',
    category: 'course',
    qualityScore: 0.74,
    scrapedAt: new Date(),
  },
  {
    title: 'ECCV 2025',
    description: 'European Conference on Computer Vision — biennial leading venue for computer vision research.',
    date: new Date('2025-09-29'),
    endDate: new Date('2025-10-04'),
    location: 'Glasgow, Scotland, UK',
    isOnline: false,
    url: 'https://eccv2025.ecva.net',
    source: 'ecva.net',
    region: 'europe',
    regionArabic: 'أوروبا',
    category: 'conference',
    qualityScore: 0.91,
    scrapedAt: new Date(),
  },
  {
    title: 'Seoul AI Week 2025',
    description: 'South Korea\'s flagship AI week — government, industry, and academia converge on AI policy and innovation.',
    date: new Date('2025-10-27'),
    endDate: new Date('2025-10-31'),
    location: 'Seoul, South Korea',
    isOnline: false,
    url: 'https://seoulaiweek.kr/2025',
    source: 'seoulaiweek.kr',
    region: 'asia',
    regionArabic: 'آسيا',
    category: 'conference',
    qualityScore: 0.83,
    scrapedAt: new Date(),
  },
  {
    title: 'AI for Climate Webinar: Satellite Imagery Analysis',
    description: 'Technical webinar on using deep learning for deforestation detection and climate monitoring.',
    date: new Date('2025-06-19'),
    endDate: new Date('2025-06-19'),
    location: null,
    isOnline: true,
    url: 'https://aiforclimate.earth/webinar/satellite-june-2025',
    source: 'aiforclimate.earth',
    region: 'worldwide',
    regionArabic: 'عالمي',
    category: 'webinar',
    qualityScore: 0.70,
    scrapedAt: new Date(),
  },
  {
    title: 'Latin America AI Summit 2025',
    description: 'First pan-Latin American AI summit — startups, academia, and government from 20+ countries.',
    date: new Date('2025-11-12'),
    endDate: new Date('2025-11-13'),
    location: 'São Paulo, Brazil',
    isOnline: false,
    url: 'https://laaisummit.com/2025',
    source: 'laaisummit.com',
    region: 'americas',
    regionArabic: 'الأمريكتان',
    category: 'summit',
    qualityScore: 0.79,
    scrapedAt: new Date(),
  },
  {
    title: 'GovAI Conclave New Delhi',
    description: 'Conference on government use of AI — policy, public services, and national AI strategies.',
    date: new Date('2025-09-15'),
    endDate: new Date('2025-09-16'),
    location: 'New Delhi, India',
    isOnline: false,
    url: 'https://govai-india.in/conclave-2025',
    source: 'govai-india.in',
    region: 'asia',
    regionArabic: 'آسيا',
    category: 'conference',
    qualityScore: 0.76,
    scrapedAt: new Date(),
  },
  {
    title: 'ISWC 2025',
    description: 'International Semantic Web Conference — knowledge graphs, linked data, and ontologies.',
    date: new Date('2025-11-02'),
    endDate: new Date('2025-11-06'),
    location: 'Amsterdam, Netherlands',
    isOnline: false,
    url: 'https://iswc2025.semanticweb.org',
    source: 'semanticweb.org',
    region: 'europe',
    regionArabic: 'أوروبا',
    category: 'conference',
    qualityScore: 0.82,
    scrapedAt: new Date(),
  },
  {
    title: 'Morocco AI Innovation Day',
    description: 'Annual gathering of Moroccan AI ecosystem — startups pitching, research talks, and networking.',
    date: new Date('2025-06-07'),
    endDate: new Date('2025-06-07'),
    location: 'Casablanca, Morocco',
    isOnline: false,
    url: 'https://moroccoai.ma/innovation-day-2025',
    source: 'moroccoai.ma',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'conference',
    qualityScore: 0.73,
    scrapedAt: new Date(),
  },
  {
    title: 'AI Agents Hackathon Global',
    description: 'Online hackathon building autonomous AI agents with tools, memory, and multi-step reasoning.',
    date: new Date('2025-08-08'),
    endDate: new Date('2025-08-10'),
    location: null,
    isOnline: true,
    url: 'https://agentshack.dev/global-2025',
    source: 'agentshack.dev',
    region: 'worldwide',
    regionArabic: 'عالمي',
    category: 'hackathon',
    qualityScore: 0.75,
    scrapedAt: new Date(),
  },
  {
    title: 'Beijing AI Conference 2025',
    description: 'China\'s premier AI research conference with focus on large language models and autonomous systems.',
    date: new Date('2025-10-18'),
    endDate: new Date('2025-10-20'),
    location: 'Beijing, China',
    isOnline: false,
    url: 'https://baai.ac.cn/conference-2025',
    source: 'baai.ac.cn',
    region: 'asia',
    regionArabic: 'آسيا',
    category: 'conference',
    qualityScore: 0.85,
    scrapedAt: new Date(),
  },
  {
    title: 'Tunis Tech Meetup: Intro to AI',
    description: 'Beginner-friendly meetup introducing machine learning concepts to the Tunisian tech community.',
    date: new Date('2025-06-28'),
    endDate: new Date('2025-06-28'),
    location: 'Tunis, Tunisia',
    isOnline: false,
    url: 'https://www.meetup.com/tunistech/events/ai-intro-june-2025',
    source: 'meetup.com',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'meetup',
    qualityScore: 0.66,
    scrapedAt: new Date(),
  },
  {
    title: 'ICCV 2025',
    description: 'International Conference on Computer Vision — biennial top-tier venue for vision research.',
    date: new Date('2025-10-19'),
    endDate: new Date('2025-10-25'),
    location: 'Honolulu, Hawaii, USA',
    isOnline: false,
    url: 'https://iccv2025.thecvf.com',
    source: 'thecvf.com',
    region: 'americas',
    regionArabic: 'الأمريكتان',
    category: 'conference',
    qualityScore: 0.92,
    scrapedAt: new Date(),
  },
  {
    title: 'AI & Robotics Forum Tel Aviv',
    description: 'Annual forum connecting Israel\'s AI and robotics ecosystem with global investors and researchers.',
    date: new Date('2025-11-25'),
    endDate: new Date('2025-11-26'),
    location: 'Tel Aviv, Israel',
    isOnline: false,
    url: 'https://airobitics-forum.il/2025',
    source: 'airobitics-forum.il',
    region: 'middle-east',
    regionArabic: 'الشرق الأوسط',
    category: 'conference',
    qualityScore: 0.81,
    scrapedAt: new Date(),
  },
  {
    title: 'NeurIPS Workshop: ML for Audio',
    description: 'NeurIPS satellite workshop on music generation, speech synthesis, and audio understanding.',
    date: new Date('2025-12-14'),
    endDate: new Date('2025-12-14'),
    location: 'New Orleans, Louisiana, USA',
    isOnline: false,
    url: 'https://neurips.cc/Conferences/2025/workshops/ml-audio',
    source: 'neurips.cc',
    region: 'americas',
    regionArabic: 'الأمريكتان',
    category: 'workshop',
    qualityScore: 0.83,
    scrapedAt: new Date(),
  },
];

async function main() {
  console.log('Seeding database with', events.length, 'events...');

  for (const event of events) {
    await prisma.event.upsert({
      where: { url: event.url ?? `no-url-${event.title}` },
      update: {},
      create: event,
    });
  }

  await prisma.scrapeRun.create({
    data: {
      apifyRunId: 'seed-run-001',
      status: 'succeeded',
      eventsFound: events.length,
      regions: JSON.stringify(['worldwide', 'middle-east', 'africa', 'europe', 'asia', 'americas']),
      startedAt: new Date(Date.now() - 180000),
      completedAt: new Date(),
      durationMs: 180000,
    },
  });

  console.log('Seed complete:', events.length, 'events inserted.');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
