import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const TUNISIA_AI_EVENTS = [
  {
    title: 'Tunisia AI Summit',
    description: "Le plus grand événement IA en Tunisie réunissant chercheurs, entrepreneurs et décideurs autour de l'intelligence artificielle.",
    date: new Date('2026-10-15'),
    location: 'Tunis, Tunisia',
    isOnline: false,
    url: 'https://tunisiaisummit.tn',
    source: 'official-website',
    region: 'africa',
    category: 'conference',
    qualityScore: 0.88,
    isTunisia: true,
    isCompetition: false,
    scrapedAt: new Date(),
  },
  {
    title: 'Smart Tunisia Hackathon AI',
    description: "Compétition nationale d'IA organisée par le Ministère des Technologies de la Communication. Équipes de 3-5 personnes.",
    date: new Date('2026-06-20'),
    location: 'Lac 2, Tunis, Tunisia',
    isOnline: false,
    url: 'https://smarttunisia.tn/hackathon',
    source: 'official-website',
    region: 'africa',
    category: 'hackathon',
    qualityScore: 0.85,
    isTunisia: true,
    isCompetition: true,
    prize: '30,000 TND + Incubation',
    eligibility: 'Résidents tunisiens, équipes de 3-5 personnes',
    howToApply: 'https://smarttunisia.tn/hackathon/apply',
    submissionDeadline: new Date('2026-06-01'),
    competitionStatus: 'open',
    scrapedAt: new Date(),
  },
  {
    title: 'Maghreb AI Conference (MAIC)',
    description: 'Annual AI conference covering North Africa and Maghreb region. Accepts research papers in Arabic, French, and English.',
    date: new Date('2026-11-05'),
    location: 'Hammamet, Tunisia',
    isOnline: false,
    url: 'https://maic-conf.org',
    source: 'official-website',
    region: 'africa',
    category: 'conference',
    qualityScore: 0.87,
    isTunisia: true,
    isCompetition: false,
    hasCfp: true,
    cfpDeadline: new Date('2026-08-15'),
    cfpUrl: 'https://maic-conf.org/cfp',
    cfpDescription: 'Papers on ML, NLP, Computer Vision, AI Ethics accepted in AR/FR/EN',
    scrapedAt: new Date(),
  },
  {
    title: "JFI - Journées Francophones d'Informatique (Tunis)",
    description: "Conférence francophone d'informatique avec track spécial Intelligence Artificielle.",
    date: new Date('2026-09-10'),
    location: 'Sfax, Tunisia',
    isOnline: false,
    url: 'https://jfi.tn',
    source: 'official-website',
    region: 'africa',
    category: 'conference',
    qualityScore: 0.82,
    isTunisia: true,
    isCompetition: false,
    hasCfp: true,
    cfpDeadline: new Date('2026-07-01'),
    scrapedAt: new Date(),
  },
  {
    title: 'Startup Tunisia AI Challenge',
    description: 'مسابقة وطنية للشركات الناشئة في مجال الذكاء الاصطناعي. مفتوحة لجميع التونسيين في العالم.',
    date: new Date('2026-07-15'),
    location: 'Online + Tunis, Tunisia',
    isOnline: true,
    url: 'https://startuptunisia.tn/ai-challenge',
    source: 'official-website',
    region: 'africa',
    category: 'hackathon',
    qualityScore: 0.84,
    isTunisia: true,
    isCompetition: true,
    prize: '$50,000 investment + 6-month acceleration',
    eligibility: 'Tunisian nationals worldwide, startups under 3 years',
    howToApply: 'https://startuptunisia.tn/apply',
    submissionDeadline: new Date('2026-06-30'),
    competitionStatus: 'open',
    scrapedAt: new Date(),
  },
  {
    title: 'AI4Tunisia — Webinar Series',
    description: 'سلسلة ندوات أونلاين شهرية حول تطبيقات الذكاء الاصطناعي في السياق التونسي والإفريقي.',
    date: new Date('2026-06-01'),
    endDate: new Date('2026-12-01'),
    location: 'Online',
    isOnline: true,
    url: 'https://ai4tunisia.org/webinars',
    source: 'official-website',
    region: 'africa',
    category: 'webinar',
    qualityScore: 0.80,
    isTunisia: true,
    isCompetition: false,
    scrapedAt: new Date(),
  },
  {
    title: 'INAT AI Research Day',
    description: "Journée de recherche en IA organisée par l'Institut National Agronomique de Tunisie — focus sur l'IA pour l'agriculture et l'environnement.",
    date: new Date('2026-05-20'),
    location: 'Tunis, Tunisia',
    isOnline: false,
    url: 'https://inat.agrinet.tn/ai-day',
    source: 'official-website',
    region: 'africa',
    category: 'conference',
    qualityScore: 0.78,
    isTunisia: true,
    isCompetition: false,
    hasCfp: true,
    cfpDeadline: new Date('2026-04-15'),
    scrapedAt: new Date(),
  },
  {
    title: 'GovTech Tunisia — AI for Public Services',
    description: 'Hackathon focused on using AI to improve government services in Tunisia. Organized by Presidency of the Republic.',
    date: new Date('2026-08-20'),
    location: 'Tunis, Tunisia',
    isOnline: false,
    url: 'https://govtech.tn/hackathon-ai',
    source: 'official-website',
    region: 'africa',
    category: 'hackathon',
    qualityScore: 0.86,
    isTunisia: true,
    isCompetition: true,
    prize: 'Integration of solution in government + 20,000 TND',
    eligibility: 'Tunisian developers and researchers',
    competitionStatus: 'upcoming',
    submissionDeadline: new Date('2026-07-31'),
    scrapedAt: new Date(),
  },
];

async function seedTunisia() {
  console.log('🇹🇳 Seeding Tunisia AI events...');
  let count = 0;
  for (const event of TUNISIA_AI_EVENTS) {
    await prisma.event.upsert({
      where: { url: event.url },
      update: event as any,
      create: event as any,
    });
    console.log(`  ✓ ${event.title}`);
    count++;
  }
  console.log(`\n✅ Seeded ${count} Tunisia AI events`);
  await prisma.$disconnect();
}

seedTunisia().catch((e) => {
  console.error(e);
  process.exit(1);
});
