import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const TUNISIA_AI_EVENTS = [
  {
    title: 'Tunisia AI Summit 2026',
    description: "أكبر حدث للذكاء الاصطناعي في تونس — يجمع باحثين وروّاد أعمال وصانعي قرار من كامل المغرب العربي وأفريقيا. Le plus grand événement IA en Tunisie.",
    date: new Date('2026-10-15'),
    location: 'Centre de Conférences, Tunis, Tunisia',
    isOnline: false,
    url: 'https://tunisiaisummit.tn',
    source: 'official-website',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'conference',
    qualityScore: 0.88,
    isTunisia: true,
    isCompetition: false,
    hasCfp: true,
    cfpDeadline: new Date('2026-08-01'),
    cfpUrl: 'https://tunisiaisummit.tn/cfp',
    cfpDescription: 'Papers on AI, ML, NLP accepted in Arabic, French, English',
    scrapedAt: new Date(),
  },
  {
    title: 'Smart Tunisia Hackathon AI 2026',
    description: "مسابقة وطنية للذكاء الاصطناعي مُنظَّمة من وزارة تكنولوجيات الاتصال. فرق من 3 إلى 5 أشخاص. Compétition nationale d'IA organisée par le Ministère des TIC.",
    date: new Date('2026-06-20'),
    location: 'Lac 2, Tunis, Tunisia',
    isOnline: false,
    url: 'https://smarttunisia.tn/hackathon',
    source: 'official-website',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'hackathon',
    qualityScore: 0.85,
    isTunisia: true,
    isCompetition: true,
    prize: '30,000 دينار تونسي + حضانة',
    prizeAmount: 30000,
    prizeCurrency: 'TND',
    eligibility: 'تونسيون مقيمون في تونس، فرق من 3 إلى 5 أشخاص',
    howToApply: 'https://smarttunisia.tn/hackathon/apply',
    submissionDeadline: new Date('2026-06-01'),
    competitionStatus: 'open',
    scrapedAt: new Date(),
  },
  {
    title: 'Maghreb AI Conference (MAIC) 2026',
    description: 'مؤتمر سنوي للذكاء الاصطناعي يغطي منطقة أفريقيا الشمالية والمغرب العربي. يقبل أوراقاً بحثية بالعربية والفرنسية والإنجليزية.',
    date: new Date('2026-11-05'),
    location: 'Hammamet, Tunisia',
    isOnline: false,
    url: 'https://maic-conf.org',
    source: 'official-website',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'conference',
    qualityScore: 0.87,
    isTunisia: true,
    isCompetition: false,
    hasCfp: true,
    cfpDeadline: new Date('2026-08-15'),
    cfpUrl: 'https://maic-conf.org/cfp',
    cfpDescription: 'Papers on ML, NLP, Computer Vision, AI Ethics accepted in AR/FR/EN',
    scrapedAt: new Date(),
  },
  {
    title: 'Startup Tunisia AI Challenge 2026',
    description: 'مسابقة وطنية للشركات الناشئة في مجال الذكاء الاصطناعي. مفتوحة لكل التونسيين في العالم. $50,000 استثمار + 6 أشهر تسريع.',
    date: new Date('2026-07-15'),
    location: 'Online + Tunis, Tunisia',
    isOnline: true,
    url: 'https://startuptunisia.tn/ai-challenge',
    source: 'official-website',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'hackathon',
    qualityScore: 0.84,
    isTunisia: true,
    isCompetition: true,
    prize: '$50,000 استثمار + 6 أشهر تسريع',
    prizeAmount: 50000,
    prizeCurrency: 'USD',
    eligibility: 'تونسيون في العالم، شركات ناشئة أقل من 3 سنوات',
    howToApply: 'https://startuptunisia.tn/apply',
    submissionDeadline: new Date('2026-06-30'),
    competitionStatus: 'open',
    scrapedAt: new Date(),
  },
  {
    title: 'GovTech Tunisia — AI for Public Services',
    description: 'هاكاثون حول استخدام الذكاء الاصطناعي لتحسين الخدمات الحكومية في تونس. منظَّم من رئاسة الجمهورية. جائزة: إدماج الحل في الإدارة.',
    date: new Date('2026-08-20'),
    location: 'Tunis, Tunisia',
    isOnline: false,
    url: 'https://govtech.tn/hackathon-ai',
    source: 'official-website',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'hackathon',
    qualityScore: 0.86,
    isTunisia: true,
    isCompetition: true,
    prize: 'إدماج الحل في الإدارة + 20,000 دينار تونسي',
    prizeAmount: 20000,
    prizeCurrency: 'TND',
    eligibility: 'مطوّرون وباحثون تونسيون',
    competitionStatus: 'upcoming',
    submissionDeadline: new Date('2026-07-31'),
    scrapedAt: new Date(),
  },
  {
    title: 'JFI — Journées Francophones d\'Informatique (Sfax 2026)',
    description: "Conférence francophone d'informatique avec track spécial Intelligence Artificielle, organisée par l'Université de Sfax.",
    date: new Date('2026-09-10'),
    location: 'Université de Sfax, Sfax, Tunisia',
    isOnline: false,
    url: 'https://jfi.tn',
    source: 'official-website',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'conference',
    qualityScore: 0.82,
    isTunisia: true,
    isCompetition: false,
    hasCfp: true,
    cfpDeadline: new Date('2026-07-01'),
    cfpUrl: 'https://jfi.tn/cfp',
    scrapedAt: new Date(),
  },
  {
    title: 'AI4Tunisia — Webinar Series 2026',
    description: 'سلسلة ندوات أونلاين شهرية حول تطبيقات الذكاء الاصطناعي في السياق التونسي والإفريقي. مجانية ومفتوحة للجميع.',
    date: new Date('2026-06-01'),
    endDate: new Date('2026-12-01'),
    location: 'Online',
    isOnline: true,
    url: 'https://ai4tunisia.org/webinars',
    source: 'official-website',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'webinar',
    qualityScore: 0.80,
    isTunisia: true,
    isCompetition: false,
    scrapedAt: new Date(),
  },
  {
    title: 'INAT AI Research Day — Agriculture & Environment',
    description: "يوم بحثي في الذكاء الاصطناعي منظَّم من المعهد الوطني الزراعي بتونس. تركيز على الذكاء الاصطناعي للفلاحة والبيئة والمياه.",
    date: new Date('2026-10-05'),
    location: 'INAT, Tunis, Tunisia',
    isOnline: false,
    url: 'https://inat.agrinet.tn/ai-day',
    source: 'official-website',
    region: 'africa',
    regionArabic: 'أفريقيا',
    category: 'conference',
    qualityScore: 0.78,
    isTunisia: true,
    isCompetition: false,
    hasCfp: true,
    cfpDeadline: new Date('2026-08-20'),
    cfpUrl: 'https://inat.agrinet.tn/ai-day/cfp',
    scrapedAt: new Date(),
  },
];

async function seedTunisia() {
  console.log('🇹🇳 Seeding Tunisia AI events...');

  // Delete existing Tunisia events first — clean slate
  const deleted = await prisma.event.deleteMany({ where: { isTunisia: true } });
  console.log(`  🗑  Deleted ${deleted.count} existing Tunisia events`);

  let count = 0;
  for (const event of TUNISIA_AI_EVENTS) {
    await prisma.event.create({ data: event as any });
    console.log(`  ✓ ${event.title}`);
    count++;
  }

  console.log(`\n✅ Seeded ${count} Tunisia-only AI events`);
  await prisma.$disconnect();
}

seedTunisia().catch((e) => {
  console.error(e);
  process.exit(1);
});
