import { Router, Request, Response } from 'express';
import { PrismaClient } from '@prisma/client';
import { requireAdminPassword } from '../middleware/auth';
import { sendTelegramAlert, sendWhatsAppAlert } from '../services/notificationService';

const router = Router();
const prisma = new PrismaClient();

// GET /api/admin/test-notify?password=xxx
router.get('/test-notify', requireAdminPassword, async (_req: Request, res: Response) => {
  const message = '🧪 Test notification from AI Festivals API\nTelegram ✅ + WhatsApp test';

  const [telegram, whatsapp] = await Promise.allSettled([
    sendTelegramAlert(message),
    sendWhatsAppAlert(message),
  ]);

  res.json({
    telegram: telegram.status === 'fulfilled' ? 'sent ✓' : `failed: ${(telegram as PromiseRejectedResult).reason?.message}`,
    whatsapp: whatsapp.status === 'fulfilled' ? 'sent ✓' : `failed: ${(whatsapp as PromiseRejectedResult).reason?.message}`,
  });
});

// POST /api/admin/seed-tunisia?password=xxx
// TEMPORARY — seeds 15 Tunisia events. Remove after use.
router.post('/seed-tunisia', requireAdminPassword, async (_req: Request, res: Response) => {
  try {
    const deleted = await prisma.event.deleteMany({ where: { isTunisia: true } });

    const TUNISIA_EVENTS = [
      // 🤖 AI
      {
        title: 'AINS 3.0 Hackathon — AI National Summit Sousse',
        description: 'Hackathon IA 48h organisé par IEEE INSAT CS SBC. Thème: IA au service des territoires. Prizes: 1ère place 2000 DT, 2ème 1500 DT, 3ème 1000 DT + 4 stages Orange Tunisia.',
        date: new Date('2025-06-13'),
        endDate: new Date('2025-06-15'),
        location: 'Sousse, Tunisia',
        isOnline: false,
        url: 'https://ains3-hackathon.devpost.com',
        source: 'official-website',
        region: 'africa',
        category: 'hackathon',
        qualityScore: 0.92,
        isTunisia: true,
        isCompetition: true,
        prize: '2000 DT (1ère) + 1500 DT (2ème) + 1000 DT (3ème) + 4 stages Orange Tunisia',
        prizeAmount: 4500,
        prizeCurrency: 'TND',
        prizeType: 'both',
        eligibility: "Étudiants et développeurs en Tunisie. Équipes max 4.",
        howToApply: 'https://ains3-hackathon.devpost.com',
        submissionDeadline: new Date('2025-06-12'),
        competitionStatus: 'closed',
        governorate: 'Sousse',
        organizerType: 'ieee',
        festivalType: 'hackathon',
        scrapedAt: new Date(),
      },
      {
        title: 'IndabaX Tunisia 2025 — Deep Learning Hackathon',
        description: "6ème édition de la conférence Deep Learning IndabaX Tunisia à El Ghazela Technopark Ariana. Hackathon IA sur la 5G et télécoms.",
        date: new Date('2025-05-03'),
        endDate: new Date('2025-05-04'),
        location: "Sup'Com, El Ghazela Technopark, Ariana",
        isOnline: false,
        url: 'https://www.indabaxtunisia.com/2025/index.html',
        source: 'official-website',
        region: 'africa',
        category: 'hackathon',
        qualityScore: 0.88,
        isTunisia: true,
        isCompetition: true,
        prize: 'Prix + Certificats IEEE',
        prizeType: 'honorary',
        competitionStatus: 'closed',
        governorate: 'Ariana',
        organizerType: 'ieee',
        festivalType: 'hackathon',
        scrapedAt: new Date(),
      },
      {
        title: 'LPKM 2026 — Conférence NLP & IA — Sousse',
        description: '4ème édition de la conférence internationale sur le NLP et la gestion des connaissances. MIRACL Lab, Université de Sfax. CFP ouvert: NLP, ML, IA, traitement du langage arabe. Soumission via CMT Microsoft.',
        date: new Date('2026-05-05'),
        endDate: new Date('2026-05-07'),
        location: 'Royal Kenz Hotel, Port El Kantaoui, Sousse',
        isOnline: false,
        url: 'https://sites.google.com/fsegs.usf.tn/lpkm-2026/',
        source: 'official-website',
        region: 'africa',
        category: 'conference',
        qualityScore: 0.91,
        isTunisia: true,
        isCompetition: false,
        hasCfp: true,
        cfpUrl: 'https://cmt3.research.microsoft.com/LPKM2026',
        cfpDescription: 'NLP, ML, IA multilingue — soumission via CMT Microsoft',
        competitionStatus: 'open',
        governorate: 'Sousse',
        organizerType: 'university',
        festivalType: 'ai',
        scrapedAt: new Date(),
      },
      {
        title: 'Orange AI Hackathon — IEEE TSYP 13 Tunisia',
        description: 'Hackathon IA 22h en télécommunications. Solutions IA pour les télécoms. IEEE Tunisia dans le cadre du congrès TSYP 13.',
        date: new Date('2026-06-15'),
        location: 'Tunis, Tunisia',
        isOnline: false,
        url: 'https://tsyp.ieee.tn/',
        source: 'official-website',
        region: 'africa',
        category: 'hackathon',
        qualityScore: 0.86,
        isTunisia: true,
        isCompetition: true,
        prize: 'Cash + Stages Orange Tunisia',
        prizeType: 'both',
        eligibility: 'Membres IEEE Student Branches Tunisie',
        howToApply: 'https://tsyp.ieee.tn/',
        competitionStatus: 'open',
        governorate: 'Tunis',
        organizerType: 'ieee',
        festivalType: 'hackathon',
        scrapedAt: new Date(),
      },
      {
        title: 'Hackathon Municipal 2026 — 50 ans, 50 innovations',
        description: 'Hackathon 24h de la Fédération Nationale des Communes Tunisiennes dans 5 villes: Djerba, Sfax, Sousse, Bizerte, Tunis. IA et numérique au service des communes.',
        date: new Date('2026-04-01'),
        location: 'Djerba / Sfax / Sousse / Bizerte / Tunis',
        isOnline: false,
        url: 'https://letemps.news/2026/05/02/cloture-du-hackathon-municipal',
        source: 'official-website',
        region: 'africa',
        category: 'hackathon',
        qualityScore: 0.87,
        isTunisia: true,
        isCompetition: true,
        prize: 'Reconnaissance + intégration projet municipal',
        prizeType: 'honorary',
        competitionStatus: 'closed',
        governorate: 'Multiple',
        organizerType: 'ministry',
        festivalType: 'hackathon',
        scrapedAt: new Date(),
      },
      // 🎬 CINEMA
      {
        title: 'أيام قرطاج السينمائية JCC 2025 — الدورة 36',
        description: 'أعرق مهرجان سينمائي في تونس والعالم العربي (1966). الدورة 36: 200+ فيلم. 9 أفلام تونسية. الجوائز: التانيت الذهبي، الفضي، البرونزي.',
        date: new Date('2025-12-13'),
        endDate: new Date('2025-12-20'),
        location: 'Théâtre Municipal Tunis + 10 villes tunisiennes',
        isOnline: false,
        url: 'https://www.jcc.tn',
        source: 'official-website',
        region: 'africa',
        category: 'conference',
        qualityScore: 0.97,
        isTunisia: true,
        isCompetition: true,
        prize: 'التانيت الذهبي (مالية + شرفية)',
        prizeType: 'both',
        competitionStatus: 'closed',
        governorate: 'Tunis + Multiple',
        organizerType: 'ministry',
        festivalType: 'cinema',
        mediaType: 'film',
        scrapedAt: new Date(),
      },
      {
        title: 'Festival CineF 2026 — Films Francophones Tunisie',
        description: "15 films de 13 pays francophones. Projections 9-25 avril 2026 aux IFT Tunis, Sousse, Sfax et B7L9 La Marsa. Belgique, France, Canada, Maroc, Côte d'Ivoire. Entrée libre.",
        date: new Date('2026-04-09'),
        endDate: new Date('2026-04-25'),
        location: 'IFT Tunis / IFT Sousse / IFT Sfax / B7L9 La Marsa',
        isOnline: false,
        url: 'https://www.webmanagercenter.com/2026/03/27/563763/',
        source: 'official-website',
        region: 'africa',
        category: 'conference',
        qualityScore: 0.90,
        isTunisia: true,
        isCompetition: false,
        competitionStatus: 'open',
        governorate: 'Tunis / Sousse / Sfax',
        organizerType: 'ngo',
        festivalType: 'cinema',
        mediaType: 'film',
        scrapedAt: new Date(),
      },
      {
        title: 'Medenine International Film Festival — Djerba',
        description: 'Festival international de cinéma à Djerba. Films tunisiens et internationaux. Compétition officielle avec trophées.',
        date: new Date('2026-09-01'),
        location: 'Djerba, Médenine',
        isOnline: false,
        url: 'https://filmfreeway.com/MedenineInternationalFilmFestival-Tunisia',
        source: 'official-website',
        region: 'africa',
        category: 'conference',
        qualityScore: 0.82,
        isTunisia: true,
        isCompetition: true,
        prize: 'Trophées + Reconnaissance',
        prizeType: 'honorary',
        howToApply: 'https://filmfreeway.com/MedenineInternationalFilmFestival-Tunisia',
        competitionStatus: 'open',
        governorate: 'Médenine',
        organizerType: 'ngo',
        festivalType: 'cinema',
        mediaType: 'film',
        scrapedAt: new Date(),
      },
      {
        title: "I-FEST² — Festival International Sciences & Technologies Tunis",
        description: "Festival de 9 jours organisé par ATAST. Compétitions de projets scientifiques et technologiques, IA inclus. Étudiants tunisiens et internationaux.",
        date: new Date('2026-07-01'),
        location: 'Tunis, Tunisia',
        isOnline: false,
        url: 'https://www.facebook.com/IFEST.TUNISIA/',
        source: 'facebook',
        region: 'africa',
        category: 'conference',
        qualityScore: 0.85,
        isTunisia: true,
        isCompetition: true,
        prize: 'Médailles + Certificats + Voyages',
        prizeType: 'honorary',
        competitionStatus: 'open',
        governorate: 'Tunis',
        organizerType: 'ngo',
        festivalType: 'cinema',
        mediaType: 'all',
        scrapedAt: new Date(),
      },
      // 📸 PHOTO
      {
        title: 'Jaou Photo Tunis — Festival Biennal Art Contemporain',
        description: 'Festival biennal dédié à la photographie, image et vidéo art. Fondation Kamel Lazaar + IFT. Expositions dans espaces non-conventionnels: médina, B7L9, quartiers populaires.',
        date: new Date('2026-10-01'),
        endDate: new Date('2026-10-20'),
        location: 'Multiple venues — B7L9, IFT, espaces publics Tunis',
        isOnline: false,
        url: 'https://www.kamellazaarfoundation.org/jaou',
        source: 'official-website',
        region: 'africa',
        category: 'conference',
        qualityScore: 0.91,
        isTunisia: true,
        isCompetition: false,
        competitionStatus: 'upcoming',
        governorate: 'Tunis',
        organizerType: 'ngo',
        festivalType: 'photo',
        mediaType: 'photo',
        scrapedAt: new Date(),
      },
      {
        title: 'Festival Arts Plastiques de Mahrès — Sfax',
        description: 'Festival annuel des arts plastiques et photographie à Mahrès. Expositions peinture, sculpture, photographie. Artistes tunisiens et internationaux. Juillet-Août.',
        date: new Date('2026-07-15'),
        endDate: new Date('2026-08-15'),
        location: 'Mahrès, Sfax',
        isOnline: false,
        url: 'https://tunis.events/en/festivals-tunisie#mahres-sfax',
        source: 'official-website',
        region: 'africa',
        category: 'conference',
        qualityScore: 0.78,
        isTunisia: true,
        isCompetition: false,
        competitionStatus: 'upcoming',
        governorate: 'Sfax',
        organizerType: 'ministry',
        festivalType: 'photo',
        mediaType: 'photo',
        scrapedAt: new Date(),
      },
      // 🎭 MIXED
      {
        title: "Dream City — Art dans l'Espace Public Tunis",
        description: "Festival biennal d'art contemporain dans la Médina de Tunis. Organisé par L'Art Rue. Performances, installations, vidéo art, photographie in situ.",
        date: new Date('2026-11-01'),
        location: 'Médina de Tunis + quartiers populaires',
        isOnline: false,
        url: 'https://www.lartrue.com/dream-city',
        source: 'official-website',
        region: 'africa',
        category: 'conference',
        qualityScore: 0.88,
        isTunisia: true,
        isCompetition: false,
        competitionStatus: 'upcoming',
        governorate: 'Tunis',
        organizerType: 'ngo',
        festivalType: 'mixed-image',
        mediaType: 'all',
        scrapedAt: new Date(),
      },
      {
        title: 'Festival International de Carthage 2026',
        description: "Plus grand festival culturel de Tunisie. Musique, théâtre, danse dans l'amphithéâtre romain de Carthage. Artistes de renommée mondiale. Juillet-Août.",
        date: new Date('2026-07-01'),
        endDate: new Date('2026-08-31'),
        location: 'Amphithéâtre de Carthage, Tunis',
        isOnline: false,
        url: 'https://www.festivaldecarthage.tn',
        source: 'official-website',
        region: 'africa',
        category: 'conference',
        qualityScore: 0.93,
        isTunisia: true,
        isCompetition: false,
        competitionStatus: 'upcoming',
        governorate: 'Tunis',
        organizerType: 'ministry',
        festivalType: 'mixed-image',
        mediaType: 'all',
        scrapedAt: new Date(),
      },
      {
        title: 'Festival International de Hammamet 2026 — 60ème édition',
        description: "60ème édition du festival le plus ancien du monde arabe. Musique, théâtre, danse au Centre Culturel International de Hammamet. Juillet-Août 2026.",
        date: new Date('2026-07-01'),
        endDate: new Date('2026-08-31'),
        location: 'Centre Culturel International, Hammamet, Nabeul',
        isOnline: false,
        url: 'https://www.festivalhammamet.com',
        source: 'official-website',
        region: 'africa',
        category: 'conference',
        qualityScore: 0.90,
        isTunisia: true,
        isCompetition: false,
        competitionStatus: 'upcoming',
        governorate: 'Nabeul',
        organizerType: 'ministry',
        festivalType: 'mixed-image',
        mediaType: 'all',
        scrapedAt: new Date(),
      },
      {
        title: "Festival Symphonique International d'El Jem",
        description: "Festival de musique classique dans l'amphithéâtre romain d'El Jem (UNESCO). Orchestre symphonique tunisien + orchestres internationaux. Été.",
        date: new Date('2026-07-20'),
        location: 'Amphithéâtre El Jem, Mahdia',
        isOnline: false,
        url: 'https://tunis.events/en/festivals-tunisie',
        source: 'official-website',
        region: 'africa',
        category: 'conference',
        qualityScore: 0.87,
        isTunisia: true,
        isCompetition: false,
        competitionStatus: 'upcoming',
        governorate: 'Mahdia',
        organizerType: 'ministry',
        festivalType: 'mixed-image',
        mediaType: 'all',
        scrapedAt: new Date(),
      },
    ] as const;

    let created = 0;
    for (const event of TUNISIA_EVENTS) {
      await prisma.event.create({ data: event as any });
      created++;
    }

    const byType: Record<string, number> = {};
    for (const e of TUNISIA_EVENTS) {
      const t = e.festivalType;
      byType[t] = (byType[t] || 0) + 1;
    }

    res.json({
      success: true,
      message: `✅ Seeded ${created} Tunisia events (deleted ${deleted.count} old)`,
      breakdown: byType,
    });

  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    res.status(500).json({ error: msg });
  }
});

export default router;
